### ISSUE TITLE
Lab 1 delivery-time review 

### ISSUE THREAD

**Issue by CarachinoAlessio** [oormacheah/CI_2022-23_304811#1]
This is a review related to the commit of 17th October with the title "recommmit bc of crash".

The solution that we employed is really similar, both are based on manipulating the Generative Search Function.

What really impressed me, is the "chain" method coming from the "itertools" package, it really simplifies the state management effectively in a case like this where we have a list of lists.

As you surely know, this algorithm won't return the optimal solution and one improvement can be changing the unit_cost and setting it equal to the len(a) (see the code snippet below).
My suggestion is to try an A* search by modifying the priority function and introducing a heuristic that takes into account how "far" the states are from the search goal.

One quick-fixable issue is related to the output of the algorithm. It logs negative "bloat". The fix could be to let the search function return both the list of reversed(path) and the final state. At this point:

```
final_path, final_state = search(
        initial_state,
        goal_test=goal_test,
        parent_state=parent_state,
        state_cost=state_cost,
        priority_function=lambda s: len(state_cost),
        #unit_cost=lambda a: 1, 
        unit_cost=lambda a: len(a)
    )

    logging.info(
        f"Found solution for N={N}: w={sum(len(_) for _ in final_state._data)} (bloat={(sum(len(_) for _ in final_state._data)-N)/N*100:.0f}%)"
    )
```

**Comment by oormacheah** [comment]
Hi Alessio, thank you for your review. Indeed the unit_cost should've been as you said, I corrected that in the later commits (after the deadline though). In the future I may try to look for this optimal heuristic function that is a bit tricky.
